# Welcome to Jekyll!
# Do not be confused by the confusing discussion of Github Pages and url and baseurl.
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CivEng112
tagline: A course on Water
description: A series of class sessions in Fall 2022
author: John Gage
baseurl: '/CivEng112' # the subpath of your site, e.g. /blog
url: 'https://coursechat.github.io' # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.5.4
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  CivEng112-Alternate Site:
    - 'https://coursechat.github.io/WaterNet/CE112_Syllabus-Fall_2022.html'
  CivEng112 on Github:
    - 'https://github.com/CourseChat/CivEng112'
footer_content:

# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      height: 300
      subpath: '/assets/staff-images/'
      width: 300
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
